version: '3.9'
services:
  db-origin:
    image: postgres:13.1
    ports:
      - "6000:5432"
    networks:
      - db-net
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
        - ./postgresql_LOGICAL.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  db-intermediate:
    image: postgres:13.1
    ports:
      - "6001:5432"
    networks:
      - db-net
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
        - ./postgresql_LOGICAL.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  db-destination:
    image: postgres:13.1
    ports:
      - "6002:5432"
    networks:
      - db-net
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin

networks:
  db-net:
    driver: bridge